name: Nodejs

on: [push]

jobs:
  cloudflare-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Sed Config Base
        shell: bash
        run: |
          # cat .env.production | base64
          # echo ${{ secrets.CONFIG }} | base64 --decode > .env.production
          sed -i  's#VITE_PUBLIC_PATH\s*=.*#VITE_PUBLIC_PATH=/yummy-backend #g' ./.env.production
          sed -i  's#VITE_GLOB_API_URL\s*=.*#VITE_GLOB_API_URL=https://ygo.fly.dev/v1#g' ./.env.production
          cat ./.env.production

      - name: Build
        env:
          CI: true
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build
          #sed -i 's#_app.config.js#yummy-backend/_app.config.js#g' dist/index.html
          #sed -i 's#/assets/#/yummy-backend/assets/#g' dist/index.html
          cp -pr dist yummy-backend

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        if: github.ref == 'refs/heads/main'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUBBOTTOKEN }}

      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUBBOTTOKEN }}
          publish_branch: gh-pages
          publish_dir: yummy-backend
